plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-readme-index
  - jekyll-relative-links

collections:
  gamepads:
    output: true
    permalink: /:path:output_ext

lsi: false

readme_index:
  remove_originals: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
